作業目標<br>
熟悉陣列維度轉換，並且會擷取需要資料<br>
作業重點<br>
使用reshap須注意order用法<br>
where可以運用邏輯條件擷取資料

題目:<br>
1.將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")<br>
2.呈上題的array，找出被6除餘1的數的索引<br>

In [1]:
import numpy as np

In [11]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")

array1 = np.array(range(30))
array2 = array1.reshape(5, 6).ravel(order='F')
array2

array([ 0,  6, 12, 18, 24,  1,  7, 13, 19, 25,  2,  8, 14, 20, 26,  3,  9,
       15, 21, 27,  4, 10, 16, 22, 28,  5, 11, 17, 23, 29])

In [14]:
#2.呈上題的array，找出被6除餘1的數的索引

index = np.where(array2 % 6 == 1)
index

(array([5, 6, 7, 8, 9]),)

In [15]:
#Test
array2[index]

array([ 1,  7, 13, 19, 25])